# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('criticalCondition', models.IntegerField()),
                ('durationTime', models.TimeField()),
                ('maxAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('current_amount', models.IntegerField()),
                ('offer_price', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cebolla.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentTypeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ingredientlocal',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cebolla.Local'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredientType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cebolla.IngredientType'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='paymentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cebolla.PaymentType'),
        ),
    ]
