# Generated by Django 2.0.5 on 2018-09-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cebolla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='scale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cebolla.IngredientType'),
        ),
    ]
