# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cebolla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('ingredientLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cebolla.IngredientLocal')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('ingredientLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cebolla.IngredientLocal')),
            ],
        ),
    ]
