# Generated by Django 2.0.5 on 2018-09-08 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebolla', '0002_auto_20180907_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='paymentType',
        ),
    ]
