# Generated by Django 2.0.5 on 2018-12-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebolla', '0002_auto_20181230_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiving',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
