# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cebolla', '0003_auto_20170805_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cebolla.Purchase'),
        ),
    ]
