# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cebolla', '0006_auto_20170805_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('A', 'Local Admin'), ('K', 'kitchen'), ('S', 'script')], max_length=1)),
                ('local', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cebolla.Local')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
