# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cebolla', '0007_globaladmin_localuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaladmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='globalAdmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localUsers', to='cebolla.Local'),
        ),
    ]
